//INPUT FIELDS
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_PASSWORD_FIELD = 'CHANGE_PASSWORD_FIELD';
export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
//LOGIN STATUS
export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCESSS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
//ROUTING
export const ROUTE_CHANGE_SIGN_IN = 'ROUTE_CHANGE_SIGN_IN';
export const ROUTE_CHANGE_REGISTER = 'ROUTE_CHANGE_REGISTER';

//REGISTER STATUS
export const REQUEST_REGISTER_PENDING = 'REQUEST_REGISTER_PENDING';
export const REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCESSS';
export const REQUEST_REGISTER_FAILED = 'REQUEST_REGISTER_FAILED';
//IMAGE API RELATED

export const CHANGE_URL_FIELD = 'CHANGE_URL_FIELD';
export const REQUEST_CLARIFAI_PENDING = 'REQUEST_CLARIFAI_PENDING';
export const REQUEST_CLARIFAI_SUCCESS = 'REQUEST_CLARIFAI_SUCCESS';
export const REQUEST_CLARIFAI_FAILED = 'REQUEST_CLARIFAI_FAILED';

export const REQUEST_COUNT_SUCCESS = 'REQUEST_COUNT_SUCCESS';
export const REQUEST_COUNT_FAILED = 'REQUEST_COUNT_FAILED';
