export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCESSS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
