//INPUT FIELDS
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_PASSWORD_FIELD = 'CHANGE_PASSWORD_FIELD';
//LOGIN STATUS
export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCESSS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
//ROUTING
export const ROUTE_CHANGE_SIGN_IN = 'ROUTE_CHANGE_SIGN_IN';
export const ROUTE_CHANGE_REGISTER = 'ROUTE_CHANGE_REGISTER';
//IMAGE API RELATED

export const CHANGE_URL_FIELD = 'CHANGE_URL_FIELD';
